imagePullSecrets: []

operators:
  downloads:
    image: thavlik/ytdl-operator:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: 128Mi
        cpu: 100m
  executors:
    image: thavlik/ytdl-operator:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: 128Mi
        cpu: 100m

executor:
  image: thavlik/ytdl-executor:latest
  imagePullPolicy: Always
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
