apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-executors
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-executors
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-executors
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
        - name: operator
          command:
            - /ytdl-operator
            - manage-executors
          imagePullPolicy: {{ .Values.operators.executors.imagePullPolicy }}
          image: {{ .Values.operators.executors.image }}
          env:
          - name: EXECUTOR_SERVICE_ACCOUNT_NAME
            value: "{{ .Release.Name }}-operator"
          - name: EXECUTOR_SPEC
            value: |
{{ toYaml .Values.executor | indent 14 }}
          resources:
{{ toYaml .Values.operators.executors.resources | indent 12 }}
