kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-operator
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-operator
  namespace:  {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-operator
  apiGroup: rbac.authorization.k8s.io