apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
- apiGroups: [""]
  resources:
  - pods/log
  verbs:
  - get
- apiGroups: ["ytdl.beebs.dev"]
  resources:
  - downloads
  - downloads/status
  - executors
  - executors/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
