apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: executors.ytdl.beebs.dev
spec:
  group: ytdl.beebs.dev
  scope: Namespaced
  names:
    kind: Executor
    listKind: ExecutorList
    plural: executors
    singular: executor
    shortNames:
      - ex
      - exec
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Status
          type: string
        - jsonPath: .status.lastUpdated
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - service
              properties: {}
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "brief description of the service's current state"
                message:
                  type: string
                  description: "longer description of the phase, such as an error message"
                lastUpdated:
                  type: string
                  description: "describes the recency of the status data"
