apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: downloads.ytdl.beebs.dev
spec:
  group: ytdl.beebs.dev
  scope: Namespaced
  names:
    kind: Download
    listKind: DownloadList
    plural: downloads
    singular: download
    shortNames:
      - dl
      - down
      - downl
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Status
          type: string
        - jsonPath: .status.lastUpdated
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - query
                - output
              properties:
                query:
                  type: string
                  description: "youtube-dl input string"
                ignoreErrors:
                  type: boolean
                  description: "ignore errors and continue downloading (-i flag)"
                output:
                  type: object
                  description: "output configuration"
                  properties:
                    video:
                      type: object
                      description: "video output configuration"
                      properties:
                        s3:
                          type: object
                          properties:
                            bucket:
                              type: string
                            secret:
                              type: string
                            endpoint:
                              type: string
                            region:
                              type: string
                            key:
                              type: string
                    thumbnail:
                      type: object
                      description: "thumbnail output configuration"
                      properties:
                        format:
                          type: string
                        width:
                          type: integer
                        height:
                          type: integer
                        filter:
                          type: string
                        s3:
                          type: object
                          required:
                            - bucket
                          properties:
                            bucket:
                              type: string
                            secret:
                              type: string
                            endpoint:
                              type: string
                            region:
                              type: string
                            key:
                              type: string
                    metadata:
                      type: object
                      description: "metadata output configuration"
                      properties:
                        mongo:
                          type: object
                          required:
                            - secret
                            - collection
                          properties:
                            secret:
                              type: string
                            collection:
                              type: string
                extra:
                  type: string
                  description: "extra youtube-dl arguments"
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "brief description of the download's current state"
                message:
                  type: string
                  description: "longer description of the phase, such as an error message"
                lastUpdated:
                  type: string
                  description: "describes the recency of the status data"
                queryStartTime:
                  type: string
                  description: "the time the query pod was started"
                queryTime:
                  type: string
                  description: "the time the query pod completed"